version: "3.8"
services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    env_file: .env
    depends_on:
      - mariadb
      - wordpress
    networks:
      - inception_net
    volumes:
      - www_volume:/var/www/html
    ports:
      - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    env_file: .env
    networks:
      - inception_net
    volumes:
      - database_volume:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception_net
    volumes:
      - www_volume:/var/www/html
    restart: always

volumes:
  www_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/sloquet/data/www_volume
      o: bind
  database_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/sloquet/data/database_volume
      o: bind

networks:
  inception_net:
    name: inception_net
    driver: bridge
