#!/bin/bash

gbar="\033[32m ---------------\033[0m"
rbar="\033[31m ---------------\033[0m"

EXEC="ircserv"
PORT=4243
PASSWORD="nopwd"

while true; do
	clear
	rm -f $EXEC
	# ~/.local/mkup
	make -j
	if [[ -x $EXEC ]]; then
		echo "../ircserv $PORT"
		echo -e $gbar
		./$EXEC $PORT $PASSWORD
	else
		echo -e $rbar
	fi
	# exit ###
	for ((i = 0; i < 8; i++)); do
		echo -n .
		sleep 1
	done
done
